server:
  port: 8086
spring:
  datasource:
  url: jdbc:mysql://localhost:3306/licensing-prod?createDatabaseIfNotExist=true
  username: root
  password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
example:
  property: This is production environment